version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
  - dependency-name: cypress
    versions:
    - 6.2.0
    - 6.3.0
  - dependency-name: ts-jest
    versions:
    - 26.5.0
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@types/cors"
    versions:
    - 2.8.9
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: ts-node-dev
    versions:
    - 1.1.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: start-server-and-test
    versions:
    - 1.11.7
