language: node_js
# node version above 12.10 is incompatible with current babel plugin. Was causing tests to fail inside of TravisCI.
# See https://github.com/QuickBase/babel-plugin-styled-components-css-namespace/issues/54
node_js:
  - 10
cache:
  directories:
    - node_modules
script:
  - yarn lint
  - yarn test
branches:
  only:
    - master
