language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
  - yarn lint
  - yarn react-scripts test --showConfig
  - yarn react-app-rewire test --showConfig
  - CI=true yarn test --debug --verbose --runInBand --detectOpenHandles
branches:
  only:
    - master
