language: node_js
node_js:
  - node
addons:
  apt:
    packages:
      # needed by Cypress, not in Ubuntu 16+ by default
      - libgconf-2-4
cache:
  directories:
    - node_modules
    - ~/.cache
script:
  - yarn lint
  - yarn test
branches:
  only:
    - master
