language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
script:
  - yarn lint
  - CI=true yarn test --listTests
  - CI=true yarn test --verbose --runInBand
branches:
  only:
    - master
